import type { Patio, PatioBounds, PlacedObject } from './types';
import { slugify } from '@/lib/utils/slugify';
import { buildPatioSlugIndex, patioFallbackSlug } from './utils/patioSlugIndex';

const DEFAULT_BOUNDS_HALF_DEG = 0.005;

/**
 * Wallet the "mine" fixtures are minted by, so the owned indicator colors (orange
 * / yellow) are reachable while developing. Swap for your own test wallet — the
 * comparison is case-insensitive. Hardhat's first dev account by default.
 * TODO: drop once patios carry a real on-chain owner.
 */
export const DEV_OWNER_ADDRESS = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266';

/** A second wallet, so "minted by someone else" is distinguishable from "unminted". */
const OTHER_OWNER_ADDRESS = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8';

type PatioFixture = Omit<Patio, 'bounds' | 'objects' | 'slug'> & {
    bounds?: PatioBounds;
    // Optional placed models. Defaults to `[]`, preserving current behavior for
    // un-seeded patios.
    objects?: PlacedObject[];
    // Optional URL slug. Derived from the name unless pinned here — set it when the
    // derived one reads badly or a legacy URL has to keep working.
    slug?: string;
};

const definePatio = (fixture: PatioFixture): Patio => {
    const { coords, bounds, objects, slug, ...rest } = fixture;
    const derivedBounds: PatioBounds = bounds ?? [
        coords.lng - DEFAULT_BOUNDS_HALF_DEG,
        coords.lat - DEFAULT_BOUNDS_HALF_DEG,
        coords.lng + DEFAULT_BOUNDS_HALF_DEG,
        coords.lat + DEFAULT_BOUNDS_HALF_DEG,
    ];
    return {
        ...rest,
        coords,
        bounds: derivedBounds,
        objects: objects ?? [],
        slug: slug || slugify(rest.name) || patioFallbackSlug(rest.id),
    };
};

const RAW_PATIOS: PatioFixture[] = [
    {
        id: '1',
        name: 'Mont Saint Michel',
        description: 'Where heaven meets the sea, faith rises above the tides',
        videoUrl: '/videos/Mont_Saint_Michel_Parallax_optimized.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Mont%20Saint%20Michel-parallax.mp4',
        previewLowUrl: '/images/patios/mont-saint-michel/preview-low.jpg',
        previewHighUrl: '/images/patios/mont-saint-michel/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Mont%20Saint%20Michel.jpg',
        previewBackgroundUrl: '/images/patios/mont-saint-michel/background.jpg',
        previewBackgroundLowUrl: '/images/patios/mont-saint-michel/background-low.jpg',
        country: 'France',
        continent: 'europe',
        type: 'landmark',
        author: 'Neos',
        ownerAddress: DEV_OWNER_ADDRESS,
        createdAt: '2025-09-12T10:00:00Z',
        popularity: 980,
        coords: { lat: 48.636, lng: -1.5114 },
        height: 0,
        // Multi-model seed: mixed catalog models inside the derived bounds, plus a
        // repeated Lantern so same-URL fetch dedupe (ResourceCache) is exercised.
        // Heights are placeholder absolute WGS84 altitudes — refine via editor pose
        // readback (see PRD absolute-height note); may float until then.
        objects: [
            {
                id: 'msm-lantern-1',
                modelId: 'lantern',
                name: 'Lantern',
                lng: -1.5115,
                lat: 48.6321,
                height: 160,
                heading: 0,
                pitch: 0,
                roll: 0,
                scale: 5,
            },
            {
                id: 'msm-lantern-2',
                modelId: 'lantern',
                name: 'Lantern',
                lng: -1.5122,
                lat: 48.6347,
                height: 60,
                heading: 180,
                pitch: 0,
                roll: 0,
                scale: 5,
            },
            {
                id: 'msm-duck-1',
                modelId: 'duck',
                name: 'Duck',
                lng: -1.5108,
                lat: 48.6364,
                height: 205,
                heading: 45,
                pitch: 0,
                roll: 0,
                scale: 20,
            },
            {
                id: 'msm-avocado-1',
                modelId: 'avocado',
                name: 'Avocado',
                lng: -1.5119,
                lat: 48.6366,
                height: 155,
                heading: 0,
                pitch: 0,
                roll: 0,
                scale: 400,
            },
        ],
        isFeatured: true,
        isPublished: true,
        blockchainLink: 'https://etherscan.io/token/0xD8dA6BF26964aF9D7eEd9e03E53415D37aA96045?a=417',
        navigationLink: 'https://maps.google.com/?q=48.636,-1.5114&mode=417',
    },
    {
        id: '2',
        name: 'National Gallery of Denmark',
        description: 'Small things done with love are greater than big things done without',
        videoUrl: '/videos/National_Gallery_of_Denmark-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/National Gallery of Denmark-parallax.mp4',
        previewLowUrl: '/images/patios/national-gallery-of-denmark/preview-low.jpg',
        previewHighUrl: '/images/patios/national-gallery-of-denmark/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/National%20Gallery%20of%20Denmark.jpg',
        previewBackgroundUrl: '/images/patios/national-gallery-of-denmark/background.jpg',
        previewBackgroundLowUrl: '/images/patios/national-gallery-of-denmark/background-low.jpg',
        country: 'Denmark',
        continent: 'europe',
        type: 'historic-site',
        author: 'Neos',
        ownerAddress: OTHER_OWNER_ADDRESS,
        createdAt: '2025-08-30T10:00:00Z',
        popularity: 1200,
        coords: { lat: 55.6885, lng: 12.5784 },
        height: 30,
        isFeatured: true,
        isPublished: true,
        blockchainLink: 'https://etherscan.io/token/0xD8dA6BF26964aF9D7eEd9e03E53415D37aA96045?a=118',
    },
    {
        id: '3',
        name: 'Elbe Philharmonic Hall',
        description: 'The soul of genius is love - and music sings it',
        videoUrl: '/videos/Elbe_Philharmonic_Hall-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Elbe%20Philharmonic%20Hall-parallax.mp4',
        previewLowUrl: '/images/patios/elbe-philharmonic-hall/preview-low.jpg',
        previewHighUrl: '/images/patios/elbe-philharmonic-hall/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Elbe%20Philharmonic%20Hall.jpg',
        previewBackgroundUrl: '/images/patios/elbe-philharmonic-hall/background.jpg',
        previewBackgroundLowUrl: '/images/patios/elbe-philharmonic-hall/background-low.jpg',
        country: 'Germany',
        continent: 'europe',
        type: 'historic-site',
        author: 'Neos',
        ownerAddress: DEV_OWNER_ADDRESS,
        createdAt: '2025-10-02T10:00:00Z',
        popularity: 540,
        coords: { lat: 53.5413, lng: 9.9842 },
        height: 30,
        isFeatured: true,
        isPublished: false,
    },
    {
        id: '4',
        name: 'Bethesda Terrace',
        description: 'Don’t be afraid to give up the good to go for the great',
        videoUrl: '/videos/Bethesda_New_York_Parallax_optimized.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Bethesda%20Terrace-parallax.mp4',
        previewLowUrl: '/images/patios/bethesda-terrace/preview-low.jpg',
        previewHighUrl: '/images/patios/bethesda-terrace/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Bethesda%20Terrace.jpg',
        previewBackgroundUrl: '/images/patios/bethesda-terrace/background.jpg',
        previewBackgroundLowUrl: '/images/patios/bethesda-terrace/background-low.jpg',
        country: 'USA',
        continent: 'north-america',
        type: 'architecture',
        author: 'Neos',
        ownerAddress: OTHER_OWNER_ADDRESS,
        createdAt: '2025-11-04T10:00:00Z',
        popularity: 1100,
        coords: { lat: 40.7741, lng: -73.9709 },
        height: 30,
        isFeatured: true,
        isPublished: true,
        navigationLink: 'https://maps.google.com/?q=40.7741,-73.9709&mode=204',
    },
    {
        id: '5',
        name: 'Castillo de Chambord',
        description: 'The art of a nation is the mirror of its soul',
        videoUrl: '/videos/Chateau_de_Chambord-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Ch%C3%A2teau%20de%20Chambord-parallax.mp4',
        previewLowUrl: '/images/patios/castillo-de-chambord/preview-low.jpg',
        previewHighUrl: '/images/patios/castillo-de-chambord/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Ch%C3%A2teau%20de%20Chambord.jpg',
        previewBackgroundUrl: '/images/patios/castillo-de-chambord/background.jpg',
        previewBackgroundLowUrl: '/images/patios/castillo-de-chambord/background-low.jpg',
        country: 'France',
        continent: 'europe',
        type: 'historic-site',
        author: 'Neos',
        ownerAddress: OTHER_OWNER_ADDRESS,
        createdAt: '2025-07-22T10:00:00Z',
        popularity: 410,
        coords: { lat: 47.6162, lng: 1.5169 },
        height: 30,
        isFeatured: true,
        isPublished: false,
    },
    {
        id: '6',
        name: 'Colosseo',
        description: 'What we do in life echoes in eternity',
        videoUrl: '/videos/Colosseo-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Colosseo-parallax.mp4',
        previewLowUrl: '/images/patios/colosseo/preview-low.jpg',
        previewHighUrl: '/images/patios/colosseo/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Colosseo.jpg',
        previewBackgroundUrl: '/images/patios/colosseo/background.jpg',
        previewBackgroundLowUrl: '/images/patios/colosseo/background-low.jpg',
        country: 'Italy',
        continent: 'europe',
        type: 'architecture',
        author: 'Neos',
        ownerAddress: DEV_OWNER_ADDRESS,
        createdAt: '2025-12-01T10:00:00Z',
        popularity: 380,
        coords: { lat: 41.8901, lng: 12.4923 },
        height: 60,
        // Multi-model seed: three distinct catalog models inside the derived bounds.
        objects: [
            {
                id: 'colosseo-box-1',
                modelId: 'box-textured',
                name: 'Box Textured',
                lng: 12.492231,
                lat: 41.890209,
                height: 160,
                heading: 0,
                pitch: 0,
                roll: 0,
                scale: 5,
            },
            {
                id: 'colosseo-duck-1',
                modelId: 'duck',
                name: 'Duck',
                lng: 12.49165,
                lat: 41.89055,
                height: 128,
                heading: 90,
                pitch: 0,
                roll: 0,
                scale: 15,
            },
            {
                id: 'colosseo-lantern-1',
                modelId: 'lantern',
                name: 'Lantern',
                lng: 12.4928,
                lat: 41.88985,
                height: 130,
                heading: 0,
                pitch: 0,
                roll: 0,
                scale: 4,
            },
        ],
        isFeatured: true,
        isPublished: true,
    },

    {
        id: '7',
        name: 'Eiffel Tower',
        description: 'A great work is not finished until it inspires those who behold it',
        videoUrl: '/videos/Eiffel_Tower-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Eiffel%20Tower-parallax.mp4',
        previewLowUrl: '/images/patios/eiffel-tower/preview-low.jpg',
        previewHighUrl: '/images/patios/eiffel-tower/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Eiffel%20Tower.jpg',
        previewBackgroundUrl: '/images/patios/eiffel-tower/background.jpg',
        previewBackgroundLowUrl: '/images/patios/eiffel-tower/background-low.jpg',
        country: 'France',
        continent: 'europe',
        type: 'landmark',
        author: 'Neos',
        createdAt: '2026-01-14T10:00:00Z',
        popularity: 760,
        coords: { lat: 48.8583, lng: 2.2945 },
        height: 0,
        isFeatured: true,
        isPublished: true,
    },
    {
        id: '8',
        name: 'Griffith Observatory',
        description: 'The universe is in us, and we are in the universe',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Griffith%20Observatory-parallax.mp4',
        previewLowUrl: '/images/patios/griffith-observatory/preview-low.jpg',
        previewHighUrl: '/images/patios/griffith-observatory/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Griffith%20Observatory.jpg',
        previewBackgroundUrl: '/images/patios/griffith-observatory/background.jpg',
        previewBackgroundLowUrl: '/images/patios/griffith-observatory/background-low.jpg',
        country: 'USA',
        continent: 'north-america',
        type: 'landmark',
        author: 'Neos',
        ownerAddress: DEV_OWNER_ADDRESS,
        createdAt: '2026-02-04T10:00:00Z',
        popularity: 220,
        coords: { lat: 34.1181, lng: -118.3003 },
        height: 50,
        isFeatured: false,
        isPublished: false,
    },
    {
        id: '9',
        name: 'Guggenheim New York',
        description: 'Progress spirals upward through effort, reflection, and resilience',
        videoUrl: '/videos/Guggenheim_Bilbao_Parallax_optimized.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Guggenheim%20New%20York-parallax.mp4',
        previewLowUrl: '/images/patios/guggenheim-new-york/preview-low.jpg',
        previewHighUrl: '/images/patios/guggenheim-new-york/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Guggenheim%20New%20York.jpg',
        previewBackgroundUrl: '/images/patios/guggenheim-new-york/background.jpg',
        previewBackgroundLowUrl: '/images/patios/guggenheim-new-york/background-low.jpg',
        country: 'USA',
        continent: 'north-america',
        type: 'architecture',
        author: 'Neos',
        ownerAddress: DEV_OWNER_ADDRESS,
        createdAt: '2026-03-01T10:00:00Z',
        popularity: 890,
        coords: { lat: 40.7829, lng: -73.9589 },
        height: 50,
        isFeatured: true,
        // Unpublished on purpose: this one lands in the hub the camera starts on, so
        // the owned-not-published (yellow) indicator is on screen from first paint.
        isPublished: false,
    },
    {
        id: '10',
        name: 'Madison Square Garden',
        description: 'New York or Nowhere - where legends are made',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Madison%20Square%20Garden-parallax.mp4',
        previewLowUrl: '/images/patios/madison-square-garden/preview-low.jpg',
        previewHighUrl: '/images/patios/madison-square-garden/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Madison%20Square%20Garden.jpg',
        previewBackgroundUrl: '/images/patios/madison-square-garden/background.jpg',
        previewBackgroundLowUrl: '/images/patios/madison-square-garden/background-low.jpg',
        country: 'USA',
        continent: 'north-america',
        type: 'stadium',
        author: 'Neos',
        ownerAddress: DEV_OWNER_ADDRESS,
        createdAt: '2025-06-18T10:00:00Z',
        popularity: 670,
        coords: { lat: 40.7505, lng: -73.9934 },
        height: 20,
        isFeatured: false,
        isPublished: true,
    },
    {
        id: '11',
        name: 'Prague Castle',
        description: 'The strongest weapon is the mind, the bravest act is justice',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Prague%20Castle-parallax.mp4',
        previewLowUrl: '/images/patios/prague-castle/preview-low.jpg',
        previewHighUrl: '/images/patios/prague-castle/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Prague%20Castle.jpg',
        previewBackgroundUrl: '/images/patios/prague-castle/background.jpg',
        previewBackgroundLowUrl: '/images/patios/prague-castle/background-low.jpg',
        country: 'Czech Republic',
        continent: 'europe',
        type: 'historic-site',
        author: 'Neos',
        ownerAddress: OTHER_OWNER_ADDRESS,
        createdAt: '2025-05-09T10:00:00Z',
        popularity: 1320,
        coords: { lat: 50.0908, lng: 14.4005 },
        height: 30,
        isFeatured: false,
        isPublished: false,
    },
    {
        id: '12',
        name: 'Sagrada Família',
        description: 'Every good tree bears good fruit',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Sagrada%20Fam%C3%ADlia-parallax.mp4',
        previewLowUrl: '/images/patios/sagrada-familia/preview-low.jpg',
        previewHighUrl: '/images/patios/sagrada-familia/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Sagrada%20Fam%C3%ADlia.jpg',
        previewBackgroundUrl: '/images/patios/sagrada-familia/background.jpg',
        previewBackgroundLowUrl: '/images/patios/sagrada-familia/background-low.jpg',
        country: 'Spain',
        continent: 'europe',
        type: 'architecture',
        author: 'Neos',
        createdAt: '2025-04-15T10:00:00Z',
        popularity: 800,
        coords: { lat: 41.4035, lng: 2.1743 },
        height: 0,
        isFeatured: false,
        isPublished: true,
    },
    {
        id: '13',
        name: 'Tōdai-ji',
        description: 'Even a small bow speaks the language of the heart',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/T%C5%8Ddai-ji-parallax.mp4',
        previewLowUrl: '/images/patios/todai-ji/preview-low.jpg',
        previewHighUrl: '/images/patios/todai-ji/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/T%C5%8Ddai-ji.jpg',
        previewBackgroundUrl: '/images/patios/todai-ji/background.jpg',
        previewBackgroundLowUrl: '/images/patios/todai-ji/background-low.jpg',
        country: 'Japan',
        continent: 'asia',
        type: 'historic-site',
        author: 'Neos',
        ownerAddress: DEV_OWNER_ADDRESS,
        createdAt: '2025-03-22T10:00:00Z',
        popularity: 1500,
        coords: { lat: 34.6884, lng: 135.8398 },
        height: 50,
        isFeatured: false,
        isPublished: false,
    },
    {
        id: '14',
        name: 'Washington Monument',
        description: 'The price of freedom is eternal vigilance',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Washington%20Monument-parallax.mp4',
        previewLowUrl: '/images/patios/washington-monument/preview-low.jpg',
        previewHighUrl: '/images/patios/washington-monument/preview.jpg',
        // previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Washington%20Monument.jpg',
        previewBackgroundUrl: '/images/patios/washington-monument/background.jpg',
        previewBackgroundLowUrl: '/images/patios/washington-monument/background-low.jpg',
        country: 'USA',
        continent: 'north-america',
        type: 'historic-site',
        author: 'Neos',
        ownerAddress: DEV_OWNER_ADDRESS,
        createdAt: '2025-02-11T10:00:00Z',
        popularity: 1700,
        coords: { lat: 38.8895, lng: -77.0352 },
        height: 0,
        isFeatured: false,
        isPublished: false,
    },
    // {
    //     id: '15',
    //     name: 'Taj Mahal',
    //     country: 'India',
    //     continent: 'asia',
    //     type: 'monument',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Taj%20Mahal.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Taj%20Mahal.jpg',
    //     author: 'Neos',
    //     createdAt: '2025-01-20T10:00:00Z',
    //     popularity: 1600,
    //     coords: { lat: 27.1751, lng: 78.0421 },
    //     isFeatured: false,
    // },
    // {
    //     id: '16',
    //     name: 'Burj Khalifa',
    //     country: 'United Arab Emirates',
    //     continent: 'asia',
    //     type: 'landmark',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Burj%20Khalifa.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Burj%20Khalifa.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-12-10T10:00:00Z',
    //     popularity: 920,
    //     coords: { lat: 35.6586, lng: 139.7454 },
    //     isFeatured: false,
    // },
    // {
    //     id: '17',
    //     name: 'Loarre Castle',
    //     country: 'Spain',
    //     continent: 'europe',
    //     type: 'historic-site',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Loarre%20Castle.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Loarre%20Castle.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-11-05T10:00:00Z',
    //     popularity: 1800,
    //     coords: { lat: 40.4319, lng: 116.5704 },
    //     isFeatured: false,
    // },
    // {
    //     id: '18',
    //     name: 'Milan Cathedral',
    //     country: 'Italy',
    //     continent: 'europe',
    //     type: 'historic-site',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Milan%20Cathedral.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Milan%20Cathedral.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-10-15T10:00:00Z',
    //     popularity: 950,
    //     coords: { lat: 39.9163, lng: 116.3972 },
    //     isFeatured: false,
    // },
    // {
    //     id: '19',
    //     name: 'Tower Bridge',
    //     country: 'UK',
    //     continent: 'europe',
    //     type: 'landmark',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Tower%20Bridge.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Tower%20Bridge.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-08-19T10:00:00Z',
    //     popularity: 1400,
    //     coords: { lat: -33.8568, lng: 151.2153 },
    //     isFeatured: false,
    // },
    // {
    //     id: '20',
    //     name: 'Sydney Opera House',
    //     country: 'Australia',
    //     continent: 'oceania',
    //     type: 'landmark',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Sydney%20Opera%20House.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Sydney%20Opera%20House.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-07-09T10:00:00Z',
    //     popularity: 600,
    //     coords: { lat: -25.3444, lng: 131.0369 },
    //     isFeatured: false,
    // },
    // {
    //     id: '21',
    //     name: 'Jeddah Tower',
    //     country: 'Saudi Arabia',
    //     continent: 'asia',
    //     type: 'park',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Jeddah%20Tower.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Jeddah%20Tower.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-06-04T10:00:00Z',
    //     popularity: 350,
    //     coords: { lat: -43.5946, lng: 170.1417 },
    //     isFeatured: false,
    // },
    // {
    //     id: '22',
    //     name: 'Louvre Abu Dhabi',
    //     country: 'United Arab Emirates',
    //     continent: 'asia',
    //     type: 'museum',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Louvre%20Abu%20Dhabi.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Louvre%20Abu%20Dhabi.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-05-12T10:00:00Z',
    //     popularity: 1750,
    //     coords: { lat: 29.9792, lng: 31.1342 },
    //     isFeatured: false,
    // },
    // {
    //     id: '23',
    //     name: 'Prince Felipe Sciences Museum',
    //     country: 'Spain',
    //     continent: 'europe',
    //     type: 'museum',
    //     previewHighUrl:
    //         'https://patiostorage.blob.core.windows.net/assets/Museu%20de%20les%20Ci%C3%A8ncies%20Pr%C3%ADncipe%20Felipe.jpg',
    //     previewBackgroundUrl:
    //         'https://patiostorage.blob.core.windows.net/assets/Museu%20de%20les%20Ci%C3%A8ncies%20Pr%C3%ADncipe%20Felipe.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-04-22T10:00:00Z',
    //     popularity: 530,
    //     coords: { lat: -33.9628, lng: 18.4098 },
    //     isFeatured: false,
    // },
];

/**
 * Slug index over the fixture set. Built once; owns collision resolution, so its values
 * carry the canonical slug each patio ended up with.
 */
export const PATIOS_SLUG_INDEX: Map<string, Patio> = buildPatioSlugIndex(RAW_PATIOS.map(definePatio));

// Sourced from the index rather than the raw list so a deduped slug can never diverge
// between what a list renders and what the URL resolves. Map preserves definition order.
export const PATIOS_FIXTURES: Patio[] = [...PATIOS_SLUG_INDEX.values()];
