import type { Patio } from './types';

export const PATIOS_FIXTURES: Patio[] = [
    {
        id: '1',
        name: 'Mont Saint Michel',
        videoUrl: '/videos/Mont_Saint_Michel-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Mont%20Saint%20Michel-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Mont%20Saint%20Michel-preview-low.jpg',
        // previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Mont%20Saint%20Michel-preview.jpg',
        previewHighUrl: '/images/parallax-patios/Mont_Saint_Michel-preview_big.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Mont%20Saint%20Michel.jpg',
        country: 'France',
        continent: 'europe',
        type: 'landmark',
        author: 'Neos',
        createdAt: '2025-09-12T10:00:00Z',
        popularity: 980,
        coords: { lat: 48.8584, lng: 2.2945 },
        isFeatured: true,
    },
    {
        id: '2',
        name: 'National Gallery of Denmark',
        videoUrl: '/videos/National_Gallery_of_Denmark-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/National Gallery of Denmark-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/National Gallery of Denmark-preview-low.jpg',
        // previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/National Gallery of Denmark-preview.jpg',
        previewHighUrl: '/images/parallax-patios/National_Gallery_of_Denmark-preview_big.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/National Gallery of Denmark.jpg',
        country: 'Denmark',
        continent: 'europe',
        type: 'historic-site',
        author: 'Neos',
        createdAt: '2025-08-30T10:00:00Z',
        popularity: 1200,
        coords: { lat: 41.8902, lng: 12.4922 },
        isFeatured: true,
    },
    {
        id: '3',
        name: 'Elbe Philharmonic Hall',
        videoUrl: '/videos/Elbe_Philharmonic_Hall-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Elbe%20Philharmonic%20Hall-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Elbe%20Philharmonic%20Hall-preview-low.jpg',
        // previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Elbe%20Philharmonic%20Hall-preview.jpg',
        previewHighUrl: '/images/parallax-patios/Elbe_Philharmonic_Hall-preview_big.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Elbe%20Philharmonic%20Hall.jpg',
        country: 'Germany',
        continent: 'europe',
        type: 'historic-site',
        author: 'Neos',
        createdAt: '2025-10-02T10:00:00Z',
        popularity: 540,
        coords: { lat: 50.0903, lng: 14.4006 },
        isFeatured: true,
    },
    {
        id: '4',
        name: 'Bethesda Terrace',
        videoUrl: '/videos/Bethesda_Terrace-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Bethesda%20Terrace-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Bethesda%20Terrace-preview-low.jpg',
        // previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Bethesda%20Terrace-preview.jpg',
        previewHighUrl: '/images/parallax-patios/Bethesda_Terrace-preview_big.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Bethesda%20Terrace.jpg',
        country: 'USA',
        continent: 'north-america',
        type: 'architecture',
        author: 'Neos',
        createdAt: '2025-11-04T10:00:00Z',
        popularity: 1100,
        coords: { lat: 41.4036, lng: 2.1744 },
        isFeatured: true,
    },
    {
        id: '5',
        name: 'Castillo de Chambord',
        videoUrl: '/videos/Chateau_de_Chambord-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Ch%C3%A2teau%20de%20Chambord-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Ch%C3%A2teau%20de%20Chambord-preview-low.jpg',
        // previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Ch%C3%A2teau%20de%20Chambord-preview.jpg',
        previewHighUrl: '/images/parallax-patios/Chateau_de_Chambord-preview_big.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Ch%C3%A2teau%20de%20Chambord.jpg',
        country: 'France',
        continent: 'europe',
        type: 'historic-site',
        author: 'Neos',
        createdAt: '2025-07-22T10:00:00Z',
        popularity: 410,
        coords: { lat: 47.616, lng: 1.5167 },
        isFeatured: true,
    },
    {
        id: '6',
        name: 'Colosseo',
        videoUrl: '/videos/Colosseo-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Colosseo-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Colosseo-preview-low.jpg',
        // previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Colosseo-preview.jpg',
        previewHighUrl: '/images/parallax-patios/Colosseo-preview_big.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Colosseo.jpg',
        country: 'Italy',
        continent: 'europe',
        type: 'architecture',
        author: 'Neos',
        createdAt: '2025-12-01T10:00:00Z',
        popularity: 380,
        coords: { lat: 53.5413, lng: 9.9842 },
        isFeatured: true,
    },
    {
        id: '7',
        name: 'Eiffel Tower',
        videoUrl: '/videos/Eiffel_Tower-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Eiffel%20Tower-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Eiffel%20Tower-preview-low.jpg',
        // previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Eiffel%20Tower-preview.jpg',
        previewHighUrl: '/images/parallax-patios/Eiffel_Tower-preview_big.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Eiffel%20Tower.jpg',
        country: 'France',
        continent: 'europe',
        type: 'landmark',
        author: 'Neos',
        createdAt: '2026-01-14T10:00:00Z',
        popularity: 760,
        coords: { lat: 43.2687, lng: -2.934 },
        isFeatured: true,
    },
    {
        id: '8',
        name: 'Griffith Observatory',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Griffith%20Observatory-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Griffith%20Observatory-preview-low.jpg',
        // previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Griffith%20Observatory-preview.jpg',
        previewHighUrl: '/images/parallax-patios/Griffith_Observatory-preview_big.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Griffith%20Observatory.jpg',
        country: 'USA',
        continent: 'north-america',
        type: 'landmark',
        author: 'Neos',
        createdAt: '2026-02-04T10:00:00Z',
        popularity: 220,
        coords: { lat: 55.6884, lng: 12.5777 },
        isFeatured: false,
    },
    {
        id: '9',
        name: 'Guggenheim New York',
        videoUrl: '/videos/Guggenheim_New_York-parallax_optimized_6_per_frame.mp4',
        // videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Guggenheim%20New%20York-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Guggenheim%20New%20York-preview-low.jpg',
        previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Guggenheim%20New%20York-preview.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Guggenheim%20New%20York.jpg',
        country: 'USA',
        continent: 'north-america',
        type: 'architecture',
        author: 'Neos',
        createdAt: '2026-03-01T10:00:00Z',
        popularity: 890,
        coords: { lat: 40.7829, lng: -73.959 },
        isFeatured: true,
    },
    {
        id: '10',
        name: 'Madison Square Garden',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Madison%20Square%20Garden-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Madison%20Square%20Garden-preview-low.jpg',
        previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Madison%20Square%20Garden-preview.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Madison%20Square%20Garden.jpg',
        country: 'USA',
        continent: 'north-america',
        type: 'stadium',
        author: 'Neos',
        createdAt: '2025-06-18T10:00:00Z',
        popularity: 670,
        coords: { lat: 38.8895, lng: -77.0353 },
        isFeatured: false,
    },
    {
        id: '11',
        name: 'Prague Castle',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Prague%20Castle-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Prague%20Castle-preview-low.jpg',
        previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Prague%20Castle-preview.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Prague%20Castle.jpg',
        country: 'Czech Republic',
        continent: 'europe',
        type: 'historic-site',
        author: 'Neos',
        createdAt: '2025-05-09T10:00:00Z',
        popularity: 1320,
        coords: { lat: 40.7829, lng: -73.9654 },
        isFeatured: false,
    },
    {
        id: '12',
        name: 'Sagrada Família',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Sagrada%20Fam%C3%ADlia-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Sagrada%20Fam%C3%ADlia-preview-low.jpg',
        previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Sagrada%20Fam%C3%ADlia-preview.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Sagrada%20Fam%C3%ADlia.jpg',
        country: 'Spain',
        continent: 'europe',
        type: 'architecture',
        author: 'Neos',
        createdAt: '2025-04-15T10:00:00Z',
        popularity: 800,
        coords: { lat: -22.912, lng: -43.2302 },
        isFeatured: false,
    },
    {
        id: '13',
        name: 'Tōdai-ji',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/T%C5%8Ddai-ji-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/T%C5%8Ddai-ji-preview-low.jpg',
        previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/T%C5%8Ddai-ji.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/T%C5%8Ddai-ji.jpg',
        country: 'Japan',
        continent: 'asia',
        type: 'historic-site',
        author: 'Neos',
        createdAt: '2025-03-22T10:00:00Z',
        popularity: 1500,
        coords: { lat: -22.9519, lng: -43.2105 },
        isFeatured: false,
    },
    {
        id: '14',
        name: 'Washington Monument',
        videoUrl: 'https://patiostorage.blob.core.windows.net/assets/Washington%20Monument-parallax.mp4',
        previewLowUrl: 'https://patiostorage.blob.core.windows.net/assets/Washington%20Monument-preview-low.jpg',
        previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Washington%20Monument-preview.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Washington%20Monument.jpg',
        country: 'USA',
        continent: 'north-america',
        type: 'historic-site',
        author: 'Neos',
        createdAt: '2025-02-11T10:00:00Z',
        popularity: 1700,
        coords: { lat: -13.1631, lng: -72.545 },
        isFeatured: false,
    },
    {
        id: '15',
        name: 'Taj Mahal',
        country: 'India',
        continent: 'asia',
        type: 'monument',
        previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Taj%20Mahal.jpg',
        previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Taj%20Mahal.jpg',
        author: 'Neos',
        createdAt: '2025-01-20T10:00:00Z',
        popularity: 1600,
        coords: { lat: 27.1751, lng: 78.0421 },
        isFeatured: false,
    },
    // {
    //     id: '16',
    //     name: 'Burj Khalifa',
    //     country: 'United Arab Emirates',
    //     continent: 'asia',
    //     type: 'landmark',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Burj%20Khalifa.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Burj%20Khalifa.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-12-10T10:00:00Z',
    //     popularity: 920,
    //     coords: { lat: 35.6586, lng: 139.7454 },
    //     isFeatured: false,
    // },
    // {
    //     id: '17',
    //     name: 'Loarre Castle',
    //     country: 'Spain',
    //     continent: 'europe',
    //     type: 'historic-site',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Loarre%20Castle.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Loarre%20Castle.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-11-05T10:00:00Z',
    //     popularity: 1800,
    //     coords: { lat: 40.4319, lng: 116.5704 },
    //     isFeatured: false,
    // },
    // {
    //     id: '18',
    //     name: 'Milan Cathedral',
    //     country: 'Italy',
    //     continent: 'europe',
    //     type: 'historic-site',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Milan%20Cathedral.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Milan%20Cathedral.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-10-15T10:00:00Z',
    //     popularity: 950,
    //     coords: { lat: 39.9163, lng: 116.3972 },
    //     isFeatured: false,
    // },
    // {
    //     id: '19',
    //     name: 'Tower Bridge',
    //     country: 'UK',
    //     continent: 'europe',
    //     type: 'landmark',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Tower%20Bridge.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Tower%20Bridge.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-08-19T10:00:00Z',
    //     popularity: 1400,
    //     coords: { lat: -33.8568, lng: 151.2153 },
    //     isFeatured: false,
    // },
    // {
    //     id: '20',
    //     name: 'Sydney Opera House',
    //     country: 'Australia',
    //     continent: 'oceania',
    //     type: 'landmark',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Sydney%20Opera%20House.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Sydney%20Opera%20House.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-07-09T10:00:00Z',
    //     popularity: 600,
    //     coords: { lat: -25.3444, lng: 131.0369 },
    //     isFeatured: false,
    // },
    // {
    //     id: '21',
    //     name: 'Jeddah Tower',
    //     country: 'Saudi Arabia',
    //     continent: 'asia',
    //     type: 'park',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Jeddah%20Tower.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Jeddah%20Tower.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-06-04T10:00:00Z',
    //     popularity: 350,
    //     coords: { lat: -43.5946, lng: 170.1417 },
    //     isFeatured: false,
    // },
    // {
    //     id: '22',
    //     name: 'Louvre Abu Dhabi',
    //     country: 'United Arab Emirates',
    //     continent: 'asia',
    //     type: 'museum',
    //     previewHighUrl: 'https://patiostorage.blob.core.windows.net/assets/Louvre%20Abu%20Dhabi.jpg',
    //     previewBackgroundUrl: 'https://patiostorage.blob.core.windows.net/assets/Louvre%20Abu%20Dhabi.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-05-12T10:00:00Z',
    //     popularity: 1750,
    //     coords: { lat: 29.9792, lng: 31.1342 },
    //     isFeatured: false,
    // },
    // {
    //     id: '23',
    //     name: 'Prince Felipe Sciences Museum',
    //     country: 'Spain',
    //     continent: 'europe',
    //     type: 'museum',
    //     previewHighUrl:
    //         'https://patiostorage.blob.core.windows.net/assets/Museu%20de%20les%20Ci%C3%A8ncies%20Pr%C3%ADncipe%20Felipe.jpg',
    //     previewBackgroundUrl:
    //         'https://patiostorage.blob.core.windows.net/assets/Museu%20de%20les%20Ci%C3%A8ncies%20Pr%C3%ADncipe%20Felipe.jpg',
    //     author: 'Neos',
    //     createdAt: '2024-04-22T10:00:00Z',
    //     popularity: 530,
    //     coords: { lat: -33.9628, lng: 18.4098 },
    //     isFeatured: false,
    // },
];
