import type { Patio } from './types';

const img = (seed: string) => {
    return `https://picsum.photos/seed/${seed}/720/480`;
};

export const PATIOS_FIXTURES: Patio[] = [
    {
        id: '1',
        name: 'Eiffel Tower',
        country: 'France',
        continent: 'europe',
        type: 'landmark',
        thumbnailUrl: img('eiffel'),
        author: 'Neos',
        createdAt: '2025-09-12T10:00:00Z',
        popularity: 980,
        coords: { lat: 48.8584, lng: 2.2945 },
        isFeatured: true,
    },
    {
        id: '2',
        name: 'Colosseum',
        country: 'Italy',
        continent: 'europe',
        type: 'historic-site',
        thumbnailUrl: img('colosseum'),
        author: 'Neos',
        createdAt: '2025-08-30T10:00:00Z',
        popularity: 1200,
        coords: { lat: 41.8902, lng: 12.4922 },
        isFeatured: true,
    },
    {
        id: '3',
        name: 'Prague Castle',
        country: 'Czechia',
        continent: 'europe',
        type: 'historic-site',
        thumbnailUrl: img('prague'),
        author: 'Neos',
        createdAt: '2025-10-02T10:00:00Z',
        popularity: 540,
        coords: { lat: 50.0903, lng: 14.4006 },
        isFeatured: true,
    },
    {
        id: '4',
        name: 'Sagrada Familia',
        country: 'Spain',
        continent: 'europe',
        type: 'architecture',
        thumbnailUrl: img('sagrada'),
        author: 'Neos',
        createdAt: '2025-11-04T10:00:00Z',
        popularity: 1100,
        coords: { lat: 41.4036, lng: 2.1744 },
        isFeatured: true,
    },
    {
        id: '5',
        name: 'Castillo de Chambord',
        country: 'France',
        continent: 'europe',
        type: 'historic-site',
        thumbnailUrl: img('chambord'),
        author: 'Neos',
        createdAt: '2025-07-22T10:00:00Z',
        popularity: 410,
        coords: { lat: 47.616, lng: 1.5167 },
        isFeatured: true,
    },
    {
        id: '6',
        name: 'Elbphilharmonie',
        country: 'Germany',
        continent: 'europe',
        type: 'architecture',
        thumbnailUrl: img('elbphil'),
        author: 'Neos',
        createdAt: '2025-12-01T10:00:00Z',
        popularity: 380,
        coords: { lat: 53.5413, lng: 9.9842 },
        isFeatured: true,
    },
    {
        id: '7',
        name: 'Guggenheim Bilbao',
        country: 'Spain',
        continent: 'europe',
        type: 'museum',
        thumbnailUrl: img('bilbao'),
        author: 'Neos',
        createdAt: '2026-01-14T10:00:00Z',
        popularity: 760,
        coords: { lat: 43.2687, lng: -2.934 },
        isFeatured: true,
    },
    {
        id: '8',
        name: 'SMK',
        country: 'Denmark',
        continent: 'europe',
        type: 'museum',
        thumbnailUrl: img('smk'),
        author: 'Neos',
        createdAt: '2026-02-04T10:00:00Z',
        popularity: 220,
        coords: { lat: 55.6884, lng: 12.5777 },
        isFeatured: true,
    },
    {
        id: '9',
        name: 'Guggenheim New York',
        country: 'USA',
        continent: 'north-america',
        type: 'museum',
        thumbnailUrl: img('guggenheim-ny'),
        author: 'Neos',
        createdAt: '2026-03-01T10:00:00Z',
        popularity: 890,
        coords: { lat: 40.7829, lng: -73.959 },
        isFeatured: true,
    },
    {
        id: '10',
        name: 'Washington Monument',
        country: 'USA',
        continent: 'north-america',
        type: 'monument',
        thumbnailUrl: img('washington'),
        author: 'Neos',
        createdAt: '2025-06-18T10:00:00Z',
        popularity: 670,
        coords: { lat: 38.8895, lng: -77.0353 },
        isFeatured: false,
    },
    {
        id: '11',
        name: 'Central Park',
        country: 'USA',
        continent: 'north-america',
        type: 'park',
        thumbnailUrl: img('centralpark'),
        author: 'Neos',
        createdAt: '2025-05-09T10:00:00Z',
        popularity: 1320,
        coords: { lat: 40.7829, lng: -73.9654 },
        isFeatured: false,
    },
    {
        id: '12',
        name: 'Maracanã',
        country: 'Brazil',
        continent: 'south-america',
        type: 'stadium',
        thumbnailUrl: img('maracana'),
        author: 'Neos',
        createdAt: '2025-04-15T10:00:00Z',
        popularity: 800,
        coords: { lat: -22.912, lng: -43.2302 },
        isFeatured: false,
    },
    {
        id: '13',
        name: 'Christ the Redeemer',
        country: 'Brazil',
        continent: 'south-america',
        type: 'monument',
        thumbnailUrl: img('redeemer'),
        author: 'Neos',
        createdAt: '2025-03-22T10:00:00Z',
        popularity: 1500,
        coords: { lat: -22.9519, lng: -43.2105 },
        isFeatured: false,
    },
    {
        id: '14',
        name: 'Machu Picchu',
        country: 'Peru',
        continent: 'south-america',
        type: 'historic-site',
        thumbnailUrl: img('machu'),
        author: 'Neos',
        createdAt: '2025-02-11T10:00:00Z',
        popularity: 1700,
        coords: { lat: -13.1631, lng: -72.545 },
        isFeatured: false,
    },
    {
        id: '15',
        name: 'Taj Mahal',
        country: 'India',
        continent: 'asia',
        type: 'monument',
        thumbnailUrl: img('taj'),
        author: 'Neos',
        createdAt: '2025-01-20T10:00:00Z',
        popularity: 1600,
        coords: { lat: 27.1751, lng: 78.0421 },
        isFeatured: false,
    },
    {
        id: '16',
        name: 'Tokyo Tower',
        country: 'Japan',
        continent: 'asia',
        type: 'landmark',
        thumbnailUrl: img('tokyo'),
        author: 'Neos',
        createdAt: '2024-12-10T10:00:00Z',
        popularity: 920,
        coords: { lat: 35.6586, lng: 139.7454 },
        isFeatured: false,
    },
    {
        id: '17',
        name: 'Great Wall',
        country: 'China',
        continent: 'asia',
        type: 'historic-site',
        thumbnailUrl: img('greatwall'),
        author: 'Neos',
        createdAt: '2024-11-05T10:00:00Z',
        popularity: 1800,
        coords: { lat: 40.4319, lng: 116.5704 },
        isFeatured: false,
    },
    {
        id: '18',
        name: 'Forbidden City',
        country: 'China',
        continent: 'asia',
        type: 'historic-site',
        thumbnailUrl: img('forbidden'),
        author: 'Neos',
        createdAt: '2024-10-15T10:00:00Z',
        popularity: 950,
        coords: { lat: 39.9163, lng: 116.3972 },
        isFeatured: false,
    },
    {
        id: '19',
        name: 'Marina Bay Sands',
        country: 'Singapore',
        continent: 'asia',
        type: 'architecture',
        thumbnailUrl: img('marina'),
        author: 'Neos',
        createdAt: '2024-09-01T10:00:00Z',
        popularity: 700,
        coords: { lat: 1.2834, lng: 103.8607 },
        isFeatured: false,
    },
    {
        id: '20',
        name: 'Sydney Opera House',
        country: 'Australia',
        continent: 'oceania',
        type: 'architecture',
        thumbnailUrl: img('sydney'),
        author: 'Neos',
        createdAt: '2024-08-19T10:00:00Z',
        popularity: 1400,
        coords: { lat: -33.8568, lng: 151.2153 },
        isFeatured: false,
    },
    {
        id: '21',
        name: 'Uluru',
        country: 'Australia',
        continent: 'oceania',
        type: 'landmark',
        thumbnailUrl: img('uluru'),
        author: 'Neos',
        createdAt: '2024-07-09T10:00:00Z',
        popularity: 600,
        coords: { lat: -25.3444, lng: 131.0369 },
        isFeatured: false,
    },
    {
        id: '22',
        name: 'Aoraki / Mount Cook',
        country: 'New Zealand',
        continent: 'oceania',
        type: 'park',
        thumbnailUrl: img('aoraki'),
        author: 'Neos',
        createdAt: '2024-06-04T10:00:00Z',
        popularity: 350,
        coords: { lat: -43.5946, lng: 170.1417 },
        isFeatured: false,
    },
    {
        id: '23',
        name: 'Pyramids of Giza',
        country: 'Egypt',
        continent: 'africa',
        type: 'historic-site',
        thumbnailUrl: img('giza'),
        author: 'Neos',
        createdAt: '2024-05-12T10:00:00Z',
        popularity: 1750,
        coords: { lat: 29.9792, lng: 31.1342 },
        isFeatured: false,
    },
    {
        id: '24',
        name: 'Table Mountain',
        country: 'South Africa',
        continent: 'africa',
        type: 'park',
        thumbnailUrl: img('tablemtn'),
        author: 'Neos',
        createdAt: '2024-04-22T10:00:00Z',
        popularity: 530,
        coords: { lat: -33.9628, lng: 18.4098 },
        isFeatured: false,
    },
    {
        id: '25',
        name: 'Marrakech Medina',
        country: 'Morocco',
        continent: 'africa',
        type: 'historic-site',
        thumbnailUrl: img('marrakech'),
        author: 'Neos',
        createdAt: '2024-03-15T10:00:00Z',
        popularity: 470,
        coords: { lat: 31.6258, lng: -7.9891 },
        isFeatured: false,
    },
    {
        id: '26',
        name: 'Louvre',
        country: 'France',
        continent: 'europe',
        type: 'museum',
        thumbnailUrl: img('louvre'),
        author: 'Neos',
        createdAt: '2024-02-28T10:00:00Z',
        popularity: 1900,
        coords: { lat: 48.8606, lng: 2.3376 },
        isFeatured: false,
    },
    {
        id: '27',
        name: 'Banksy Wall',
        country: 'UK',
        continent: 'europe',
        type: 'art',
        thumbnailUrl: img('banksy'),
        author: 'Neos',
        createdAt: '2024-01-15T10:00:00Z',
        popularity: 280,
        coords: { lat: 51.5074, lng: -0.1278 },
        isFeatured: false,
    },
    {
        id: '28',
        name: 'Wembley Stadium',
        country: 'UK',
        continent: 'europe',
        type: 'stadium',
        thumbnailUrl: img('wembley'),
        author: 'Neos',
        createdAt: '2023-12-20T10:00:00Z',
        popularity: 660,
        coords: { lat: 51.556, lng: -0.2796 },
        isFeatured: false,
    },
    {
        id: '29',
        name: 'Brooklyn Bridge',
        country: 'USA',
        continent: 'north-america',
        type: 'landmark',
        thumbnailUrl: img('brooklyn'),
        author: 'Neos',
        createdAt: '2023-11-08T10:00:00Z',
        popularity: 850,
        coords: { lat: 40.7061, lng: -73.9969 },
        isFeatured: false,
    },
    {
        id: '30',
        name: 'Yosemite Valley',
        country: 'USA',
        continent: 'north-america',
        type: 'park',
        thumbnailUrl: img('yosemite'),
        author: 'Neos',
        createdAt: '2023-10-01T10:00:00Z',
        popularity: 990,
        coords: { lat: 37.7456, lng: -119.5936 },
        isFeatured: false,
    },
];
