/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiKitRouteImport } from './routes/ui-kit'
import { Route as CreatePatioRouteImport } from './routes/create-patio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatiosSlugIndexRouteImport } from './routes/patios.$slug.index'
import { Route as PatiosSlugEditRouteImport } from './routes/patios.$slug.edit'

const UiKitRoute = UiKitRouteImport.update({
  id: '/ui-kit',
  path: '/ui-kit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ui-kit.lazy').then((d) => d.Route))
const CreatePatioRoute = CreatePatioRouteImport.update({
  id: '/create-patio',
  path: '/create-patio',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/create-patio.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const PatiosSlugIndexRoute = PatiosSlugIndexRouteImport.update({
  id: '/patios/$slug/',
  path: '/patios/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatiosSlugEditRoute = PatiosSlugEditRouteImport.update({
  id: '/patios/$slug/edit',
  path: '/patios/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-patio': typeof CreatePatioRoute
  '/ui-kit': typeof UiKitRoute
  '/patios/$slug/edit': typeof PatiosSlugEditRoute
  '/patios/$slug/': typeof PatiosSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-patio': typeof CreatePatioRoute
  '/ui-kit': typeof UiKitRoute
  '/patios/$slug/edit': typeof PatiosSlugEditRoute
  '/patios/$slug': typeof PatiosSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-patio': typeof CreatePatioRoute
  '/ui-kit': typeof UiKitRoute
  '/patios/$slug/edit': typeof PatiosSlugEditRoute
  '/patios/$slug/': typeof PatiosSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-patio'
    | '/ui-kit'
    | '/patios/$slug/edit'
    | '/patios/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-patio' | '/ui-kit' | '/patios/$slug/edit' | '/patios/$slug'
  id:
    | '__root__'
    | '/'
    | '/create-patio'
    | '/ui-kit'
    | '/patios/$slug/edit'
    | '/patios/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatePatioRoute: typeof CreatePatioRoute
  UiKitRoute: typeof UiKitRoute
  PatiosSlugEditRoute: typeof PatiosSlugEditRoute
  PatiosSlugIndexRoute: typeof PatiosSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-kit': {
      id: '/ui-kit'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-patio': {
      id: '/create-patio'
      path: '/create-patio'
      fullPath: '/create-patio'
      preLoaderRoute: typeof CreatePatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patios/$slug/': {
      id: '/patios/$slug/'
      path: '/patios/$slug'
      fullPath: '/patios/$slug/'
      preLoaderRoute: typeof PatiosSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patios/$slug/edit': {
      id: '/patios/$slug/edit'
      path: '/patios/$slug/edit'
      fullPath: '/patios/$slug/edit'
      preLoaderRoute: typeof PatiosSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatePatioRoute: CreatePatioRoute,
  UiKitRoute: UiKitRoute,
  PatiosSlugEditRoute: PatiosSlugEditRoute,
  PatiosSlugIndexRoute: PatiosSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
